version: "3.7"
services:
  app:
    image: adessilly/php-composer:latest
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - 8888:8888
    volumes:
      - ./:/var/www

  db:
    image: mariadb:latest
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravelDB
      MYSQL_ROOT_PASSWORD: adminroot
      MYSQL_PASSWORD: user01
      MYSQL_USER: user01
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    links:
      - db
    ports:
      - "8889:80"
